### ISSUE TITLE
HN client source?

### ISSUE THREAD

**Issue by idc77** [kyoto-framework/kyoto#126]
In the readme is a link to the hn client for poc/demo purposes. Is the source available anywhere?

**Comment by yuriizinets** [comment]
To be honest, it's pretty outdated. You can find it here: https://github.com/yuriizinets/kyoto-hn
Live demo: https://hn.kyoto.codes
It's been a long time since I've created that HN client, so it's still using old architecture that will be removed in v1.0.
Mainly I'm developing library for team's internal purposes and have no time to do everything well in public space (like, documentation, good demo, documenting edge cases, best practices, etc).
If you'll have any questions, feel free to ask directly.

**Comment by idc77** [comment]
Thank you.
