### ISSUE TITLE
Up-to-date on Using the UIKit

### ISSUE THREAD

**Issue by jim380** [kyoto-framework/kyoto#132]
Hi guys,

First of all, just wanted to take a moment and express my gratitude to your guys for making Kyoto a reality. It's awesome and really makes a lot sense for gophers to build out frontends on the fly. That said, I was wondering if you guys had any updated docs on using the UIKit. So far all the docs and demo projects I've come across were on an older version of the codebase and the apis have changed quite a bit since then. Would love some guidance here. Thanks in advance.

Best,
Jay

**Comment by yuriizinets** [comment]
Hi, Jay!
I'm very glad for your kind words!

Now I'm focusing on 1.0 release for main library, it's a main priority for me. 
A lot of things were improved during a long period of time and still don't have tagged 1.0 stable release.

Won't lie, `kyoto-framework/kyoto` documentation is not good enough to be "production ready". It's not full, not covers some features and concept things yet. Status of `kyoto-framework/uikit` documentation is even worse IMO, it's just a layout/template for a future documentation. Overall UIKit project was a PoC for us, so now we need to improve it a lot. Please, use it carefully.

I'm the only maintainer of this project on free time. Also, we have a nice guy @RowdyHcs who helps sometimes.
Unfortunately, we have a hard situation due to war in Ukraine. Without going into details, we have to focus on our main job now and don't have enough free time. Anyway, I'm trying to push some major updates sometimes.

Let me compose a small updates roadmap:
- Stable 1.0 release.
- Define best practices, features use cases, etc. We don't have much things to tell yet, but would be nice to explain how we are using this library in our project at least.
- `kyoto-framework/uikit`, package review and documentation update. I'm not going to delay it, as far as you're asking about up-to-date docs :)
- `kyoto-framework/i18n`, documentation. Here (https://github.com/kyoto-framework/i18n/issues/1) you can check reasons why we spent some time on providing this package.
-`kyoto-framework/icons` minor improvements. We like icons. We are using icons, and we like to use them inline with template function.

Sorry, if I didn't matched your expectations :) 
Don't hesitate to contact me directly with telegram (@yuriizinets) or email (yurii.zinets@icloud.com) in case of any questions, ready to help you any time.

**Comment by jim380** [comment]
Let me hit you on Telegram. I'd love to see if and how I can help the project move forward.

**Comment by yuriizinets** [comment]
As far as a concept is changing (yes, again, it's better to do that before 1.0), I'm focusing on library itself now.
I think I've provided some information on plans, so I'm closing this issue for now.
Anyway, don't hesitate to contact me anytime!
