### ISSUE TITLE
Package clientside JS Payload using esbuild golang version

### ISSUE THREAD

**Issue by gedw99** [kyoto-framework/kyoto#96]
**Is your feature request related to a problem? Please describe.**

Its faster and its golang so you have deep control of what it does.

**Describe the solution you'd like**

Here is example code of its usage from https://github.com/tmc/goloz/blob/master/Makefile

````

go get github.com/evanw/esbuild/cmd/esbuild


esbuild \
		client/$(SOURCEPATH)/index.js \
		'--define:process.env.NODE_ENV="development"' \
		--sourcemap \
		--serve=8000 --servedir=docs --outfile=$(OUTPATH)/app.js --bundle

````

**Describe alternatives you've considered**

...

**Additional context**

Its faster. way faster.
You get nice sourcemaps still.
Its well used now and even JS devs are starting to use it. SO i dont think its going away.
we can mix and match JS and WASM compilation in any way we need to since its golang lib where we have full control.

**Comment by yuriizinets** [comment]
I don't really understand a difference between existing approach and your proposal. We are already using esbuild for building TS code. You can find it [here](https://github.com/kyoto-framework/kyoto/blob/master/payload/package.json).  
After building, payload is packaging into .go file with package.js (thanks to @RowdyHcs) because go packaging system can't include non-go files. After that, payload can be injected into page with dynamics template function.

**Comment by gedw99** [comment]
Oppsy i missed that :) all good then ...
